server:
  port: ${SERVER_PORT:8080}

logbook:
  filter:
    enabled: ${LOGBOOK_FILTER_ENABLED:true}
  format:
    style: json
  include: /**

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:ERROR}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
